// =============================================================
// Cognitia AI — Blog Post Data (single source of truth)
// =============================================================

export interface BlogPost {
  slug: string
  title: string
  description: string
  date: string
  author: string
  readTime: string
  category: string
  tags: string[]
  ogImage?: string
  content: string // HTML content
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'multi-model-orchestration-why-one-ai-isnt-enough',
    title: 'Multi-Model Orchestration: Why One AI Isn\'t Enough',
    description:
      'GPT excels at creative writing. Claude dominates complex reasoning. Gemini leads in multimodal tasks. Cognitia AI runs them all in parallel so your business gets the best answer every time.',
    date: '2026-05-09',
    author: 'Cognitia AI',
    readTime: '8 min read',
    category: 'Technology',
    tags: ['multi-model', 'AI orchestration', 'GPT', 'Claude', 'Gemini'],
    content: `
<p>Most AI platforms lock you into a single model. You pick GPT or Claude, and every task — from drafting emails to analyzing contracts — runs through that one model's strengths and weaknesses. It's like hiring a single employee and expecting them to be world-class at marketing, engineering, accounting, and design simultaneously.</p>

<p>That's the fundamental problem Cognitia AI was built to solve.</p>

<h2>The Model Specialization Problem</h2>

<p>Every large language model has a personality — a set of tasks where it dramatically outperforms alternatives, and others where it falls short:</p>

<ul>
<li><strong>GPT-5.4</strong> excels at creative content generation, marketing copy, and conversational fluency. It's the model you want writing your email campaigns and social media posts.</li>
<li><strong>Claude Opus 4.6</strong> dominates in complex multi-step reasoning, code generation, and tasks requiring deep context retention. When you need an AI that can hold 200,000 tokens of context and reason through a legal contract, Claude is your pick.</li>
<li><strong>Gemini 3.1 Pro</strong> leads in multimodal understanding — processing images, video, and audio alongside text. It's also Google's native model for search-integrated tasks.</li>
<li><strong>Claude Haiku 4.5 / GPT-5.4 Mini</strong> are speed-optimized. For high-volume tasks like classifying support tickets or extracting structured data from forms, these smaller models deliver results in milliseconds at a fraction of the cost.</li>
</ul>

<p>Running every task through a single model means you're always compromising. Your creative copy is being generated by a reasoning model, or your data analysis is being handled by a creative model. Either way, you're leaving performance on the table.</p>

<h2>How Cognitia AI Orchestrates Multiple Models</h2>

<p>Cognitia AI's orchestration layer acts as an intelligent router. When you send a message — "Draft three versions of our product launch email, then analyze which one will convert best based on our customer data" — the system doesn't send the entire task to one model.</p>

<p>Instead, it decomposes the task:</p>

<ol>
<li><strong>Creative generation</strong> (email drafts) → routed to GPT-5.4, which produces three distinct versions with different tones and angles</li>
<li><strong>Analytical reasoning</strong> (conversion analysis) → routed to Claude Opus 4.6, which cross-references the drafts against your customer segments, purchase history, and past email performance</li>
<li><strong>Results synthesis</strong> → a lightweight model combines the outputs into a clear recommendation with confidence scores</li>
</ol>

<p>All three steps happen in parallel when possible. The user sees a single, coherent response — they never need to think about which model handled what.</p>

<h2>The Persistent Memory Advantage</h2>

<p>Orchestration without memory is just fancy routing. What makes Cognitia's approach different is that every model in the chain has access to the same persistent memory layer. When Claude analyzes your email conversion rates, it's drawing on the same customer knowledge that GPT used to write the drafts.</p>

<p>This shared context means:</p>

<ul>
<li>Models don't contradict each other (they're working from the same facts)</li>
<li>Follow-up questions don't require re-explaining context</li>
<li>The system gets smarter over time as more interactions build the knowledge graph</li>
</ul>

<h2>Real-World Impact: The Numbers</h2>

<p>In internal benchmarks across 1,000+ real business tasks, multi-model orchestration delivers:</p>

<ul>
<li><strong>34% better quality scores</strong> on creative + analytical combination tasks vs. single-model execution</li>
<li><strong>2.1x faster processing</strong> on parallelizable workflows (e.g., generate content while simultaneously analyzing data)</li>
<li><strong>41% cost reduction</strong> by routing simple tasks to lightweight models instead of always using the most expensive option</li>
</ul>

<p>The cost reduction alone often pays for the entire platform. Most businesses are running every classification task and data extraction through GPT-4 or Claude Opus — models that cost 10-50x more than their smaller counterparts with zero quality difference for those specific tasks.</p>

<h2>What This Means for Your Business</h2>

<p>You don't need to become an AI expert. You don't need to evaluate models, manage API keys, or build routing logic. Cognitia AI handles the orchestration layer so you can focus on what matters: telling the AI what you need done.</p>

<p>The right model for the job, every time, automatically. That's what multi-model orchestration delivers.</p>

<p><a href="/#contact">→ See how multi-model orchestration can automate your workflows</a></p>
`,
  },
  {
    slug: 'persistent-memory-the-ai-that-remembers-everything',
    title: 'Persistent Memory: The AI That Remembers Everything',
    description:
      'Most AI assistants forget you the moment the chat window closes. Cognitia AI\'s persistent memory layer means your AI knows your business, your preferences, and your history — across every conversation.',
    date: '2026-05-08',
    author: 'Cognitia AI',
    readTime: '7 min read',
    category: 'Technology',
    tags: ['persistent memory', 'knowledge graph', 'AI memory', 'context'],
    content: `
<p>Open ChatGPT. Ask it to write a follow-up email to a client you discussed yesterday. It has no idea what you're talking about. Every conversation starts from zero.</p>

<p>This is the dirty secret of most AI tools: they have amnesia. And it's costing businesses hours every week in repeated context-setting, re-explaining preferences, and fixing outputs that ignore information the AI should already know.</p>

<h2>The Context Window Illusion</h2>

<p>Modern language models advertise massive context windows — 200K tokens, sometimes more. This creates the illusion of memory. You can paste an entire document into the chat and the model will reference it. But close that chat window and open a new one? Gone.</p>

<p>Context windows are short-term memory. What businesses actually need is long-term memory — an AI that accumulates knowledge about your company, your clients, your preferences, and your processes over weeks and months of interaction.</p>

<h2>How Cognitia AI's Memory Layer Works</h2>

<p>Every interaction with Cognitia AI feeds into a persistent knowledge graph. This isn't a simple chat log — it's a structured, queryable representation of everything the AI has learned about your business:</p>

<ul>
<li><strong>Entity recognition</strong> — The system automatically identifies and tracks people, companies, projects, and products mentioned across all conversations</li>
<li><strong>Relationship mapping</strong> — It understands that "Sarah from Acme Corp" is the same person whether you call her "Sarah," "the Acme contact," or "our biggest client's PM"</li>
<li><strong>Preference learning</strong> — After three rounds of feedback on email tone, the AI knows you prefer direct, concise language over flowery prose</li>
<li><strong>Cross-modal memory</strong> — Information from emails, calendar events, uploaded documents, and conversations are all unified into the same knowledge graph</li>
</ul>

<h2>The Memory Explorer</h2>

<p>Cognitia AI includes a visual Memory Explorer — a knowledge graph visualization that lets you see exactly what your AI knows. You can:</p>

<ul>
<li>Browse entities and their relationships</li>
<li>See which conversations contributed specific knowledge</li>
<li>Manually correct or remove information</li>
<li>Export your knowledge graph (you own your data — more on that in our data ownership article)</li>
</ul>

<p>This transparency is critical. An AI with hidden memory is a liability. An AI with transparent, auditable memory is a tool you can trust.</p>

<h2>Practical Examples</h2>

<p><strong>Scenario 1: Client Follow-Up</strong></p>
<p>You: "Draft a follow-up to the proposal I sent DataVault last week."</p>
<p>Without memory: "I don't have context about a proposal to DataVault. Could you provide details?"</p>
<p>With Cognitia's memory: "Here's a follow-up referencing the 3-month pilot proposal at $4,200/mo you sent to Marcus Chen at DataVault on May 2nd. I've included the two concerns he raised in your last call (integration timeline and SSO support) with responses…"</p>

<p><strong>Scenario 2: Content Consistency</strong></p>
<p>You: "Write this week's LinkedIn post about our new feature."</p>
<p>Without memory: Generic feature announcement that doesn't match your brand voice.</p>
<p>With Cognitia's memory: Post that matches your established LinkedIn tone (professional but conversational), references the product narrative you've been building across previous posts, and avoids the three competitors you've asked to never mention.</p>

<p><strong>Scenario 3: Team Onboarding</strong></p>
<p>A new team member starts using Cognitia AI. The AI already knows the company's products, clients, processes, and preferences — because it learned them from the team's collective interactions. The new hire is productive from day one.</p>

<h2>Privacy by Design</h2>

<p>Persistent memory raises a critical question: who controls this information?</p>

<p>At Cognitia AI, the answer is unambiguous: you do. Your memory data is:</p>

<ul>
<li>Encrypted at rest and in transit</li>
<li>Never used to train models</li>
<li>Exportable at any time in standard formats</li>
<li>Deletable — permanently, not just hidden</li>
</ul>

<p>The Memory Explorer isn't just a feature — it's a promise. You can see, audit, and control everything your AI knows about you.</p>

<h2>The Compounding Returns of Memory</h2>

<p>The longer you use Cognitia AI, the better it gets. Not because the models improve (though they do), but because your personal knowledge graph deepens. After six months, your AI assistant understands your business better than most new hires would after their first year.</p>

<p>That's the real unlock: an AI that gets better at helping <em>you</em>, specifically, every single day.</p>

<p><a href="/#contact">→ Start building your AI's memory today</a></p>
`,
  },
  {
    slug: 'data-ownership-thesis-your-data-your-rules',
    title: 'The Data Ownership Thesis: Your Data, Your Rules',
    description:
      'Every interaction with AI generates valuable data. Most platforms keep it. Cognitia AI gives it back to you — with the option to monetize it on your terms.',
    date: '2026-05-07',
    author: 'Cognitia AI',
    readTime: '9 min read',
    category: 'Philosophy',
    tags: ['data ownership', 'privacy', 'data monetization', 'marketplace'],
    content: `
<p>Here's an uncomfortable truth about most AI platforms: every prompt you write, every document you upload, every preference you express — it all becomes training data for the next model version. Your competitive intelligence, your client details, your business processes — absorbed into a model that your competitors also use.</p>

<p>Cognitia AI was built on the opposite principle. We call it the Data Ownership Thesis, and it's foundational to everything we build.</p>

<h2>The Three Principles</h2>

<h3>1. Your Data Is Never Training Data</h3>

<p>This isn't buried in a terms of service footnote. It's an architectural decision. Cognitia AI's persistent memory layer is completely isolated from the language models we orchestrate. GPT, Claude, and Gemini process your queries, but your conversation history, knowledge graph, and uploaded documents are never sent back to model providers as training data.</p>

<p>How we enforce this:</p>

<ul>
<li>API calls to model providers include only the current query and necessary context — never your full history</li>
<li>Your knowledge graph lives in your own encrypted data partition</li>
<li>We use enterprise API agreements with every model provider that explicitly prohibit training on customer data</li>
</ul>

<h3>2. Full Portability</h3>

<p>You can export your entire Cognitia AI dataset at any time:</p>

<ul>
<li>Knowledge graph in standard JSON-LD format</li>
<li>Conversation history in Markdown</li>
<li>Uploaded documents with metadata</li>
<li>AI-generated content and analyses</li>
<li>Memory connections and entity relationships</li>
</ul>

<p>If you decide to leave Cognitia AI, your data leaves with you. No lock-in, no export fees, no 30-day waiting periods. Your data, your timeline.</p>

<h3>3. Optional Monetization</h3>

<p>This is where the thesis gets interesting. Your interactions with AI generate valuable data patterns — anonymized insights about workflows, industry best practices, market signals. Cognitia AI's data marketplace lets you choose to monetize these patterns:</p>

<ul>
<li><strong>Consent-first</strong> — Nothing is shared without your explicit, granular approval. You choose what to share and what stays private.</li>
<li><strong>Anonymized by default</strong> — Shared data is stripped of personally identifiable information before it enters the marketplace</li>
<li><strong>Revenue sharing via Stripe</strong> — When your anonymized data patterns are accessed by other users or researchers, you earn a share of the revenue</li>
<li><strong>Revocable at any time</strong> — Changed your mind? Pull your data from the marketplace instantly</li>
</ul>

<h2>Why This Matters for Businesses</h2>

<p>For most businesses, the data ownership question isn't philosophical — it's practical:</p>

<p><strong>Compliance.</strong> If you're in healthcare, finance, legal, or government, you likely have regulatory obligations about where your data goes. Cognitia AI's isolated architecture means your data stays within defined boundaries, not mixed into a global training corpus.</p>

<p><strong>Competitive advantage.</strong> Your AI gets better over time because of your specific business context. If that context leaks into a shared model, your competitors benefit from your institutional knowledge. With Cognitia AI, your knowledge graph is yours alone.</p>

<p><strong>Vendor independence.</strong> Full data portability means you're never locked into Cognitia AI. If a better platform emerges in five years, you take your accumulated knowledge with you. This isn't altruism — it's a bet that if we have to earn your business every month, we'll build a better product.</p>

<h2>The Technical Architecture</h2>

<p>Under the hood, data ownership is enforced through several architectural choices:</p>

<ul>
<li><strong>Tenant isolation</strong> — Each customer's knowledge graph lives in a dedicated partition with encryption keys derived from their account. Even Cognitia AI engineers cannot access your data without your explicit grant.</li>
<li><strong>JWT-authenticated MCP endpoints</strong> — Your data is accessible via secure API endpoints that you control. Build integrations, export data, or connect to external tools — all with standard, auditable authentication.</li>
<li><strong>Audit logging</strong> — Every access to your data is logged. You can see who (or what) accessed your information, when, and why.</li>
</ul>

<h2>The Marketplace Vision</h2>

<p>The data marketplace is still early. But the vision is clear: a world where individuals and businesses are compensated for the data they generate, rather than having it extracted for free by platform companies.</p>

<p>Today, you can opt into sharing anonymized workflow patterns. Tomorrow, we're building towards industry-specific data cooperatives — groups of businesses in the same sector who share anonymized insights to collectively improve their AI capabilities while maintaining individual data ownership.</p>

<p>Your data built the AI revolution. It's time you got paid for it.</p>

<p><a href="/#contact">→ Learn more about data ownership at Cognitia AI</a></p>
`,
  },
  {
    slug: 'ai-automation-small-business-1500-starting-point',
    title: 'AI Automation for Small Business: The $1,500 Starting Point',
    description:
      'You don\'t need a six-figure budget to start automating with AI. Here\'s how small businesses are saving 20+ hours per week starting at $1,500.',
    date: '2026-05-06',
    author: 'Cognitia AI',
    readTime: '6 min read',
    category: 'Business',
    tags: ['small business', 'automation', 'ROI', 'workflows'],
    content: `
<p>The AI automation industry has a pricing problem. Enterprise platforms charge $10,000/month. Consultants quote six-figure implementation projects. The message to small businesses is clear: this isn't for you yet.</p>

<p>We disagree. Here's what $1,500 actually buys — and why the ROI makes it one of the best investments a small business can make.</p>

<h2>What a $1,500 Automation Looks Like</h2>

<p>The Starter package at Cognitia AI delivers one custom AI automation workflow, fully built and deployed. Here are the most common ones small businesses request:</p>

<p><strong>Lead Qualification Bot</strong></p>
<p>An AI agent that monitors your contact form submissions, website chat, and email inbox. It instantly qualifies leads based on criteria you define (budget, timeline, fit), sends qualified leads to your CRM with a priority score, and auto-responds to unqualified inquiries with helpful resources. Result: you only spend time on leads that can actually buy.</p>

<p><strong>Email Follow-Up Automation</strong></p>
<p>After every client meeting, the AI drafts a personalized follow-up email based on meeting notes (or a recording transcript). It includes action items, next steps, and relevant attachments. You review and send in 30 seconds instead of spending 15 minutes crafting each follow-up.</p>

<p><strong>Invoice Processing Pipeline</strong></p>
<p>Incoming invoices (email attachments, uploaded PDFs) are automatically parsed, categorized, matched to projects, and entered into your accounting software. Discrepancies are flagged for human review. The AI handles the 90% of invoices that are straightforward; you handle the exceptions.</p>

<p><strong>Content Repurposing Engine</strong></p>
<p>Write one blog post. The AI automatically generates: a LinkedIn post, three tweets, an email newsletter snippet, and an Instagram caption — all in your brand voice (because persistent memory knows your tone). Saves 3-5 hours per piece of content.</p>

<h2>The ROI Math</h2>

<p>Let's be conservative. A single automation saves 5 hours per week (most save 8-15, but let's use 5).</p>

<ul>
<li>5 hours/week × 50 weeks = 250 hours/year saved</li>
<li>At $50/hour (a modest billing rate for most businesses), that's $12,500 in recovered time</li>
<li>ROI: 733% in the first year</li>
</ul>

<p>Even at minimum wage in most provinces, the math works. At $17/hour, 250 hours = $4,250 saved — still a 183% return on a $1,500 investment.</p>

<p>And unlike hiring, the automation doesn't take vacation, doesn't need training refreshers, and doesn't slow down during busy periods. It scales linearly.</p>

<h2>What's Included</h2>

<p>The $1,500 Starter package isn't a template you configure yourself. It includes:</p>

<ul>
<li><strong>Discovery call</strong> — We map your current workflow and identify the highest-impact automation opportunity</li>
<li><strong>Custom development</strong> — Your automation is built from scratch for your specific tools, data, and processes</li>
<li><strong>Integration</strong> — Connected to your existing CRM, email, calendar, or accounting software</li>
<li><strong>30-day support</strong> — Post-launch optimization, bug fixes, and tuning based on real usage</li>
<li><strong>Performance dashboard</strong> — See exactly how many hours the automation is saving</li>
<li><strong>Documentation</strong> — Complete guide so your team understands the workflow</li>
</ul>

<h2>When to Upgrade</h2>

<p>Most businesses start with one automation, see the impact, and expand. The Growth plan ($3,500/month) includes up to five automations, a custom AI chatbot, and ongoing optimization. But the Starter is designed to prove the concept without a monthly commitment.</p>

<p>No subscription. No lock-in. Build one automation, measure the results, decide if you want more.</p>

<h2>Getting Started</h2>

<p>The process is simple:</p>

<ol>
<li><strong>Tell us your biggest time sink</strong> — What repetitive task eats your week?</li>
<li><strong>We design the automation</strong> — Custom workflow diagram, timeline, and scope</li>
<li><strong>Build and deploy</strong> — Usually 5-10 business days from kickoff to live</li>
<li><strong>30 days of support</strong> — We tune and optimize based on real usage</li>
</ol>

<p>No AI expertise required. If you can describe the task, we can automate it.</p>

<p><a href="/#pricing">→ View pricing and get started</a></p>
`,
  },
  {
    slug: 'from-chatbot-to-full-stack-ai-agent',
    title: 'From Chatbot to Full-Stack AI Agent: The Evolution of Business AI',
    description:
      'Chatbots answer questions. AI agents take action. Here\'s how Cognitia AI\'s agent architecture goes beyond conversation to actually execute workflows across your entire tech stack.',
    date: '2026-05-05',
    author: 'Cognitia AI',
    readTime: '10 min read',
    category: 'Technology',
    tags: ['AI agents', 'automation', 'chatbots', 'integrations', 'MCP'],
    content: `
<p>In 2023, every business wanted a chatbot. Stick an AI on your website, let it answer FAQs, maybe qualify a lead or two. It was the gateway drug to AI adoption — easy to implement, easy to understand, hard to measure real impact.</p>

<p>Three years later, chatbots feel quaint. The frontier has moved to AI agents: autonomous systems that don't just converse but <em>act</em>. They send emails, update CRMs, schedule meetings, process payments, generate reports, and orchestrate entire workflows — all without human intervention for routine tasks.</p>

<p>This is the evolution Cognitia AI was built for.</p>

<h2>The Chatbot Ceiling</h2>

<p>Chatbots hit a ceiling fast. They can:</p>

<ul>
<li>Answer questions from a knowledge base</li>
<li>Route visitors to the right department</li>
<li>Collect basic contact information</li>
</ul>

<p>They cannot:</p>

<ul>
<li>Check your CRM and personalize responses based on the visitor's account history</li>
<li>Actually book a meeting on your calendar</li>
<li>Send a follow-up email with the right attachment after the conversation</li>
<li>Update a project management tool with new requirements from the chat</li>
<li>Process a payment and issue a receipt</li>
</ul>

<p>The gap between "answering questions" and "getting things done" is where most AI implementations stall. Cognitia AI bridges that gap.</p>

<h2>The Agent Architecture</h2>

<p>A Cognitia AI agent is fundamentally different from a chatbot. It has three capabilities that chatbots lack:</p>

<h3>1. Tool Use</h3>

<p>Agents can use tools — integrations with external services that let them take real-world actions. Out of the box, Cognitia AI agents can:</p>

<ul>
<li><strong>Email</strong> — Read, compose, and send emails via Gmail, Outlook, or iCloud Mail</li>
<li><strong>Calendar</strong> — Check availability, book meetings, send invites via Google Calendar or Outlook Calendar</li>
<li><strong>Cloud Storage</strong> — Read, create, and organize files on Google Drive, OneDrive, or Dropbox</li>
<li><strong>Finance</strong> — Check account balances and transaction history via Plaid</li>
<li><strong>Social Media</strong> — Post to X/Twitter, LinkedIn, and Telegram</li>
<li><strong>Browser Automation</strong> — Navigate websites, fill forms, extract data from pages that don't have APIs</li>
</ul>

<p>A single user message can trigger actions across multiple tools simultaneously. "Schedule a meeting with the DataVault team next week, send them the updated proposal, and post on LinkedIn about our new enterprise tier" — one message, three tools, zero manual work.</p>

<h3>2. Persistent Memory</h3>

<p>Unlike chatbots that forget context between sessions, agents maintain a knowledge graph that accumulates over time. The agent knows who your clients are, what projects are in flight, your communication preferences, and the history of every interaction. This transforms tool use from generic to personalized.</p>

<h3>3. Multi-Model Reasoning</h3>

<p>When an agent needs to decide <em>which</em> action to take, it can leverage different AI models for different aspects of the decision. Creative tasks go to GPT. Analytical reasoning goes to Claude. The agent's orchestration layer routes automatically.</p>

<h2>The MCP Marketplace</h2>

<p>Beyond built-in integrations, Cognitia AI supports the Model Context Protocol (MCP) — an open standard for connecting AI agents to external tools and services. The MCP Marketplace lets you:</p>

<ul>
<li>Connect to any MCP-compatible service (and the ecosystem is growing rapidly)</li>
<li>Build custom MCP servers for your proprietary tools</li>
<li>Share integrations with the community</li>
</ul>

<p>This means if your business runs on a niche ERP system, a custom database, or an internal tool — you can build an MCP bridge and your Cognitia AI agent will use it natively alongside Gmail, Slack, and everything else.</p>

<h2>The Local Device Bridge</h2>

<p>One of Cognitia AI's most distinctive capabilities is the companion desktop app. Most AI platforms are cloud-only — they can't touch anything on your local machine. Cognitia AI's desktop bridge connects the cloud AI to your local environment:</p>

<ul>
<li>Access local files without uploading them to the cloud</li>
<li>Run local scripts and tools</li>
<li>Interact with desktop applications</li>
<li>Bridge between cloud services and local development environments</li>
</ul>

<p>For developers and power users, this is transformative. Your AI agent can check a local Git repository, review recent commits, run tests, and push changes — all from a natural language command.</p>

<h2>What This Means in Practice</h2>

<p>Here's a real workflow a Cognitia AI agent handles end-to-end:</p>

<ol>
<li>An email arrives from a prospective client asking about pricing</li>
<li>The agent checks the CRM — the prospect visited the pricing page three times this week and downloaded a case study</li>
<li>Based on the prospect's company size and industry (pulled from enrichment data), the agent selects the most relevant pricing tier</li>
<li>It drafts a personalized response referencing the case study they downloaded, includes a calendar link for a demo, and CCs the account manager</li>
<li>The agent creates a deal in the CRM, sets a follow-up reminder for 3 days, and logs the interaction</li>
<li>All of this happens in under 60 seconds, with zero human involvement</li>
</ol>

<p>That's not a chatbot answering a question. That's an AI agent running a sales workflow.</p>

<h2>The Path Forward</h2>

<p>The chatbot era trained businesses to think of AI as a conversation partner. The agent era reframes AI as a <em>coworker</em> — one that can be delegated real tasks with real consequences.</p>

<p>Cognitia AI is built for this future. Multi-model orchestration for intelligence. Persistent memory for context. Tool use for action. Data ownership for trust.</p>

<p>The question isn't whether AI agents will replace chatbots. They already have. The question is whether your business is ready to delegate.</p>

<p><a href="/#contact">→ Build your first AI agent with Cognitia AI</a></p>
`,
  },
]

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}

export function getAllPosts(): BlogPost[] {
  return [...blogPosts].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  )
}
